=== andungtra/he-thong-quan-ly-tuong-tac/trunk/SourceCode/src/test/java/ProcessTemplateSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">
	<xs:simpleType name="xBuildInType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="String"></xs:enumeration>
			<xs:enumeration value="Integer"></xs:enumeration>
			<xs:enumeration value="Double"></xs:enumeration>
			<xs:enumeration value="DateTime"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="xWorkItems">
		<xs:sequence>
			<xs:element name="xWorkItem" maxOccurs="unbounded" type="xWorkItem"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="xWorkItem">
		<xs:sequence>
			<xs:element name="xPreDefinedFields" type="xPreDefinedFields"></xs:element>
			<xs:element name="xAddionalFields" type="xAddionalFields"></xs:element>
		</xs:sequence>
		<xs:attribute name="refName" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="xPreDefinedFields">
		<xs:sequence>
			<xs:element name="xField" type="xField" maxOccurs="unbounded"
				minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="xAddionalFields">
		<xs:sequence>
			<xs:element name="xField" type="xField" maxOccurs="unbounded"
				minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="xChoices">
		<xs:sequence>
			<xs:element name="xChoice" maxOccurs="unbounded" type="xs:string">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="xField">
		<xs:choice>
			<xs:element name="xChoices" minOccurs="0" type="xChoices">
			</xs:element>
			<xs:element name="xDefaultValue" type="xs:string"></xs:element>
		</xs:choice>
		<xs:attribute name="refName" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="type" type="xBuildInType" use="required"></xs:attribute>
		<xs:attribute name="regex" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="xProjectProcess">
		<xs:sequence>
			<xs:element name="xWorkItems" type="xWorkItems"></xs:element>
			<xs:element name="xDescription"></xs:element>
		</xs:sequence>
		<xs:attribute name="identity" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>
	<xs:element name="xProjectProcess" type="xProjectProcess"></xs:element>
	<xs:complexType name="xFieldImpl" mixed="true">
		<xs:attribute name="ref" use="required"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="xAdditionalFieldsImpl">
		<xs:sequence>
			<xs:element name="xField" maxOccurs="unbounded" minOccurs="0"
				type="xFieldImpl"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="xAdditionalFields" type="xAdditionalFieldsImpl"></xs:element>
</xs:schema>

=== andungtra/he-thong-quan-ly-tuong-tac/trunk/SourceCode/src/main/java/WaterFall.xml
<?xml version="1.0"?>
<xProjectProcess identity="waterfall" name="Waterfall"
	xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com ProcessTemplateSchema.xsd">
	<xWorkItems>
		<xWorkItem name="Task" refName="task">
			<xPreDefinedFields></xPreDefinedFields>
			<xAddionalFields></xAddionalFields>
		</xWorkItem>
		<xWorkItem refName="requirement" name="Requirement">
			<xPreDefinedFields></xPreDefinedFields>
			<xAddionalFields>
				<xField refName="risk" name="Risk" type="digits" requied="true">
				</xField>
				<xField refName="difficulty" name="Difficulty" type="digits"></xField>
				<xField refName="costToComplete" name="Cost to complete"
					type="number"></xField>
			</xAddionalFields>
		</xWorkItem>
		<xWorkItem name="Defect" refName="defect">
			<xPreDefinedFields></xPreDefinedFields>
			<xAddionalFields>
				<xField name="Severity" type="string" refName="severity">
					<xChoices>
						<xChoice>High</xChoice>
						<xChoice>Low</xChoice>
					</xChoices>
				</xField>
				<xField name="Environment" type="string" refName="environment">
					<xDefaultValue>fas</xDefaultValue>
				</xField>
				<xField name="type" type="string" refName="type"></xField>
			</xAddionalFields>
		</xWorkItem>
	</xWorkItems>
	<xDescription>Des</xDescription>
</xProjectProcess>

=== andungtra/he-thong-quan-ly-tuong-tac/SourceCode/src/main/java/ScrumTemplate.xml
<?xml version="1.0"?>
<xProjectProcess identity="scrum" name="Scrum" xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com ProcessTemplateSchema.xsd">
	<xWorkItems>
		<xWorkItem refName="userStory" name="User story">
			<xPreDefinedFields></xPreDefinedFields>
			<xAddionalFields>
				<xField refName="storyPoint" name="Story point" type="Integer">
				</xField>
				<xField refName="difficulty" name="Difficulty" type="Integer"></xField>
			</xAddionalFields>
		</xWorkItem>
		<xWorkItem name="bug" refName="Bug">
			<xPreDefinedFields></xPreDefinedFields>
			<xAddionalFields>
				<xField name="Severity" type="String" refName="severity"></xField>
				<xField name="Environment" type="String" refName="environment"></xField>
				<xField name="type" type="String" refName="type"></xField>
			</xAddionalFields>
		</xWorkItem>
	</xWorkItems>
	<xDescription>Des</xDescription>
</xProjectProcess>

=== andungtra/he-thong-quan-ly-tuong-tac/trunk/SourceCode/src/test/java/ScrumTemplate.xml
<?xml version="1.0"?>
<xProjectProcess identity="waterfall" name="Waterfall" xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com ProcessTemplateSchema.xsd">
	<xWorkItems>
		<xWorkItem refName="requirement" name="Requirement">
			<xPreDefinedFields></xPreDefinedFields>
			<xAddionalFields>
				<xField refName="risk" name="Risk" type="Integer">
				</xField>
				<xField refName="difficulty" name="Difficulty" type="Integer"></xField>
				<xField refName="costToComplete" name="Cost to complete" type="Integer"></xField>
			</xAddionalFields>
		</xWorkItem>
		<xWorkItem name="Defect" refName="defect">
			<xPreDefinedFields></xPreDefinedFields>
			<xAddionalFields>
				<xField name="Severity" type="String" refName="severity">
					<xChoices>
						<xChoice>Critical</xChoice>
						<xChoice>Normal</xChoice>
					</xChoices>
				</xField>
				<xField name="Environment" type="String" refName="environment">
					<xDefaultValue>defaultvalue</xDefaultValue>
				</xField>
				<xField name="type" type="String" refName="type"></xField>
			</xAddionalFields>
		</xWorkItem>
	</xWorkItems>
	<xDescription>Des</xDescription>
</xProjectProcess>
